
###
POST https://didactic-halibut-q7pxpr6qv64g346j7-3001.app.github.dev/api/login
Content-Type: application/json

{
    "username": "devil child",
    "password": "adventureland"
}

###
POST https://didactic-halibut-q7pxpr6qv64g346j7-3001.app.github.dev/api/login
Content-Type: application/json

{
    "username": "goody goody",
    "password": "goodluck"
}