POST https://didactic-halibut-q7pxpr6qv64g346j7-3001.app.github.dev/api/notes
Content-Type: application/json
Authorization: Bearer 

{
    "content": "The last move of Ted is touching",
    "important": false
}

// No empty line between Request and Header(Content-Type)
// Multiple requests can be achieved by ### delimiter